// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi2ZqpYdE7Yg7peFCQvl3bVXb1rFKqJp4',
    appId: '1:191471603356:web:e9055579efdf087418e759',
    messagingSenderId: '191471603356',
    projectId: 'my-shamba-1236b',
    authDomain: 'my-shamba-1236b.firebaseapp.com',
    storageBucket: 'my-shamba-1236b.firebasestorage.app',
    measurementId: 'G-3JZC2ZTVBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm9XMJ8xMoR3KbEdMGmK630gFE2U4hT0Q',
    appId: '1:191471603356:android:ae4ae8849581bca718e759',
    messagingSenderId: '191471603356',
    projectId: 'my-shamba-1236b',
    storageBucket: 'my-shamba-1236b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx_Of6e134-md4-ujXLJMxl2FkNis-Ejc',
    appId: '1:191471603356:ios:a90e19c96208df7618e759',
    messagingSenderId: '191471603356',
    projectId: 'my-shamba-1236b',
    storageBucket: 'my-shamba-1236b.firebasestorage.app',
    iosBundleId: 'com.example.myShamba',
  );
}
